// data.js
// This file is the single source of truth for dashboard data.
// LOGIN_DATA is auto-generated by pull_mixpanel.py --update-dashboard

export const WEEKS = ["Mar 2", "Mar 9", "Mar 16", "Mar 23", "Mar 30"];
export const WEEK_KEYS = ["2026-03-02", "2026-03-09", "2026-03-16", "2026-03-23", "2026-03-30"];
export const CLIENT_LOGINS = {
  "Badia Spice LLC": "Mar 30",
  "Conagra": "Mar 30",
  "Mills": "Mar 30",
  "Shelby Erectors": "Mar 30",
  "Southern Tree": null,
  "Steel Service": "Mar 30",
  "Stella Jones": "Mar 30",
  "Stutsman": "Mar 23",
  "Thrift Holdings": "Mar 30",
  "Tippmann": "Mar 30",
  "XPO": "Mar 30",
  "Yellow Cab": "Mar 30"
};
export const TOTAL_CLIENTS = 12;

export const LOGIN_DATA = [
  { week: "Mar 2",  n: 10,  active: 12 },
  { week: "Mar 9",  n: 11,  active: 12 },
  { week: "Mar 16",  n: 11,  active: 12 },
  { week: "Mar 23",  n: 10,  active: 12 },
  { week: "Mar 30",  n: 10,  active: 12 }
].map(d => ({ ...d, pct: Math.round(d.n / d.active * 100) }));
export const SITE_DATA = {
  "Badia Spice LLC": {
    "1400": {
      "2026-02-16": { alerts:257, avg_daily:36.7, fp_rate:0.88, total:25, good:3 },
      "2026-02-23": { alerts:130, avg_daily:18.6, fp_rate:0.6, total:5, good:2 },
      "2026-03-02": { alerts:144, avg_daily:20.6, fp_rate:0.375, total:8, good:5 },
      "2026-03-09": { alerts:133, avg_daily:19.0, fp_rate:null, total:0, good:0 },
      "2026-03-16": { alerts:96, avg_daily:19.2, fp_rate:0.0, total:1, good:1 },
    },
    "2200": {
      "2026-02-23": { alerts:22, avg_daily:3.1, fp_rate:null, total:0, good:0 },
      "2026-03-02": { alerts:82, avg_daily:11.7, fp_rate:1.0, total:3, good:0 },
      "2026-03-09": { alerts:79, avg_daily:11.3, fp_rate:0.333, total:3, good:2 },
      "2026-03-16": { alerts:66, avg_daily:13.2, fp_rate:null, total:0, good:0 },
    },
  },
  "Conagra": {
    "Imlay City": {
      "2026-02-02": { alerts:9, avg_daily:1.3, fp_rate:null, total:0, good:0 },
      "2026-02-16": { alerts:11, avg_daily:1.6, fp_rate:0.0, total:1, good:1 },
      "2026-02-23": { alerts:7, avg_daily:1.0, fp_rate:null, total:0, good:0 },
      "2026-03-02": { alerts:5, avg_daily:0.7, fp_rate:null, total:0, good:0 },
      "2026-03-09": { alerts:6, avg_daily:0.9, fp_rate:0.0, total:1, good:1 },
    },
    "St. Elmo": {
      "2026-02-02": { alerts:4, avg_daily:0.6, fp_rate:0.5, total:4, good:2 },
      "2026-02-09": { alerts:3, avg_daily:0.4, fp_rate:null, total:0, good:0 },
      "2026-02-16": { alerts:5, avg_daily:0.7, fp_rate:1.0, total:2, good:0 },
      "2026-02-23": { alerts:5, avg_daily:0.7, fp_rate:0.0, total:5, good:5 },
      "2026-03-02": { alerts:12, avg_daily:1.7, fp_rate:0.0, total:4, good:4 },
      "2026-03-09": { alerts:47, avg_daily:6.7, fp_rate:0.0, total:6, good:6 },
      "2026-03-16": { alerts:16, avg_daily:3.2, fp_rate:1.0, total:1, good:0 },
    },
  },
  "Mills": {
    "Mills Mexico": {
      "2026-03-16": { alerts:20, avg_daily:4.0, fp_rate:0.5, total:8, good:4 },
    },
    "Mills USA": {
      "2026-02-02": { alerts:8, avg_daily:1.1, fp_rate:0.667, total:3, good:1 },
      "2026-02-09": { alerts:19, avg_daily:2.7, fp_rate:0.0, total:1, good:1 },
      "2026-02-16": { alerts:132, avg_daily:18.9, fp_rate:0.5, total:10, good:5 },
      "2026-02-23": { alerts:124, avg_daily:17.7, fp_rate:0.5, total:4, good:2 },
      "2026-03-02": { alerts:104, avg_daily:14.9, fp_rate:0.5, total:4, good:2 },
      "2026-03-09": { alerts:79, avg_daily:11.3, fp_rate:0.875, total:8, good:1 },
      "2026-03-16": { alerts:59, avg_daily:11.8, fp_rate:0.917, total:12, good:1 },
    },
  },
  "Shelby Erectors": {
    "Foreman Anibal S": {
      "2026-02-02": { alerts:7, avg_daily:1.0, fp_rate:1.0, total:3, good:0 },
      "2026-02-09": { alerts:5, avg_daily:0.7, fp_rate:null, total:0, good:0 },
      "2026-02-16": { alerts:11, avg_daily:1.6, fp_rate:0.667, total:3, good:1 },
      "2026-02-23": { alerts:13, avg_daily:1.9, fp_rate:0.333, total:6, good:4 },
      "2026-03-02": { alerts:1, avg_daily:0.1, fp_rate:0.0, total:1, good:1 },
      "2026-03-09": { alerts:8, avg_daily:1.1, fp_rate:0.5, total:4, good:2 },
      "2026-03-16": { alerts:8, avg_daily:1.6, fp_rate:null, total:0, good:0 },
    },
    "Foreman Jose Soto Hector": {
      "2026-02-02": { alerts:7, avg_daily:1.0, fp_rate:1.0, total:3, good:0 },
      "2026-02-09": { alerts:4, avg_daily:0.6, fp_rate:null, total:0, good:0 },
      "2026-02-16": { alerts:8, avg_daily:1.1, fp_rate:0.2, total:5, good:4 },
      "2026-02-23": { alerts:5, avg_daily:0.7, fp_rate:0.667, total:3, good:1 },
      "2026-03-02": { alerts:10, avg_daily:1.4, fp_rate:0.4, total:5, good:3 },
      "2026-03-09": { alerts:13, avg_daily:1.9, fp_rate:0.0, total:9, good:9 },
      "2026-03-16": { alerts:8, avg_daily:1.6, fp_rate:0.0, total:1, good:1 },
    },
    "Main Camera - Job 295": {
      "2026-02-02": { alerts:5, avg_daily:0.7, fp_rate:null, total:0, good:0 },
      "2026-02-09": { alerts:3, avg_daily:0.4, fp_rate:null, total:0, good:0 },
      "2026-02-16": { alerts:13, avg_daily:1.9, fp_rate:0.5, total:6, good:3 },
      "2026-02-23": { alerts:6, avg_daily:0.9, fp_rate:0.333, total:3, good:2 },
      "2026-03-02": { alerts:11, avg_daily:1.6, fp_rate:0.167, total:6, good:5 },
      "2026-03-09": { alerts:8, avg_daily:1.1, fp_rate:0.0, total:2, good:2 },
      "2026-03-16": { alerts:13, avg_daily:2.6, fp_rate:0.0, total:1, good:1 },
    },
  },
  "Steel Service": {
    "Steel Service": {
      "2026-01-26": { alerts:16, avg_daily:2.3, fp_rate:null, total:0, good:0 },
      "2026-02-02": { alerts:75, avg_daily:10.7, fp_rate:0.562, total:16, good:7 },
      "2026-02-09": { alerts:111, avg_daily:15.9, fp_rate:0.786, total:14, good:3 },
      "2026-02-16": { alerts:139, avg_daily:19.9, fp_rate:1.0, total:15, good:0 },
      "2026-02-23": { alerts:100, avg_daily:14.3, fp_rate:0.846, total:13, good:2 },
      "2026-03-02": { alerts:100, avg_daily:14.3, fp_rate:0.875, total:16, good:2 },
      "2026-03-09": { alerts:94, avg_daily:13.4, fp_rate:0.889, total:18, good:2 },
      "2026-03-16": { alerts:74, avg_daily:14.8, fp_rate:0.75, total:8, good:2 },
    },
  },
  "Stella Jones": {
    "Stella Jones": {
      "2026-01-26": { alerts:2, avg_daily:0.3, fp_rate:0.5, total:2, good:1 },
      "2026-02-02": { alerts:33, avg_daily:4.7, fp_rate:0.593, total:27, good:11 },
      "2026-02-09": { alerts:33, avg_daily:4.7, fp_rate:0.652, total:23, good:8 },
      "2026-02-16": { alerts:19, avg_daily:2.7, fp_rate:0.6, total:15, good:6 },
      "2026-02-23": { alerts:13, avg_daily:1.9, fp_rate:0.455, total:11, good:6 },
      "2026-03-02": { alerts:23, avg_daily:3.3, fp_rate:0.524, total:21, good:10 },
      "2026-03-09": { alerts:26, avg_daily:3.7, fp_rate:0.571, total:14, good:6 },
      "2026-03-16": { alerts:19, avg_daily:3.8, fp_rate:0.438, total:16, good:9 },
    },
  },
  "Stutsman": {
    "Stutsman - pilot": {
      "2026-01-26": { alerts:2, avg_daily:0.3, fp_rate:null, total:0, good:0 },
      "2026-02-02": { alerts:41, avg_daily:5.9, fp_rate:1.0, total:1, good:0 },
      "2026-02-09": { alerts:29, avg_daily:4.1, fp_rate:1.0, total:2, good:0 },
      "2026-02-16": { alerts:47, avg_daily:6.7, fp_rate:0.6, total:5, good:2 },
      "2026-02-23": { alerts:31, avg_daily:4.4, fp_rate:0.6, total:25, good:10 },
      "2026-03-02": { alerts:38, avg_daily:5.4, fp_rate:0.484, total:31, good:16 },
      "2026-03-09": { alerts:49, avg_daily:7.0, fp_rate:0.524, total:21, good:10 },
      "2026-03-16": { alerts:37, avg_daily:7.4, fp_rate:1.0, total:1, good:0 },
    },
  },
  "Tippmann": {
    "Indiana Packers DC-2": {
      "2026-02-02": { alerts:4, avg_daily:0.6, fp_rate:1.0, total:1, good:0 },
      "2026-02-09": { alerts:20, avg_daily:2.9, fp_rate:0.6, total:5, good:2 },
      "2026-02-16": { alerts:40, avg_daily:5.7, fp_rate:0.733, total:15, good:4 },
      "2026-02-23": { alerts:33, avg_daily:4.7, fp_rate:0.6, total:5, good:2 },
      "2026-03-02": { alerts:48, avg_daily:6.9, fp_rate:0.778, total:9, good:2 },
      "2026-03-09": { alerts:47, avg_daily:6.7, fp_rate:0.304, total:46, good:32 },
      "2026-03-16": { alerts:42, avg_daily:8.4, fp_rate:0.19, total:42, good:34 },
    },
  },
  "XPO": {
    "Leicester": {
      "2026-02-02": { alerts:157, avg_daily:22.4, fp_rate:0.933, total:15, good:1 },
      "2026-02-09": { alerts:118, avg_daily:16.9, fp_rate:0.762, total:21, good:5 },
      "2026-02-16": { alerts:148, avg_daily:21.1, fp_rate:0.636, total:11, good:4 },
      "2026-02-23": { alerts:154, avg_daily:22.0, fp_rate:0.375, total:8, good:5 },
      "2026-03-02": { alerts:134, avg_daily:19.1, fp_rate:0.909, total:11, good:1 },
      "2026-03-09": { alerts:162, avg_daily:23.1, fp_rate:0.526, total:19, good:9 },
      "2026-03-16": { alerts:112, avg_daily:22.4, fp_rate:0.6, total:10, good:4 },
    },
  },
  "Yellow Cab": {
    "Wendy's 1017 - East York": {
      "2026-02-09": { alerts:79, avg_daily:11.3, fp_rate:0.846, total:13, good:2 },
      "2026-02-16": { alerts:111, avg_daily:15.9, fp_rate:1.0, total:6, good:0 },
      "2026-02-23": { alerts:181, avg_daily:25.9, fp_rate:0.5, total:6, good:3 },
      "2026-03-02": { alerts:176, avg_daily:25.1, fp_rate:0.5, total:2, good:1 },
      "2026-03-09": { alerts:172, avg_daily:24.6, fp_rate:null, total:0, good:0 },
      "2026-03-16": { alerts:102, avg_daily:20.4, fp_rate:null, total:0, good:0 },
    },
    "Wendy's 2074 - Hamburg": {
      "2026-02-09": { alerts:80, avg_daily:11.4, fp_rate:0.571, total:7, good:3 },
      "2026-02-16": { alerts:114, avg_daily:16.3, fp_rate:0.143, total:7, good:6 },
      "2026-02-23": { alerts:193, avg_daily:27.6, fp_rate:0.0, total:2, good:2 },
      "2026-03-02": { alerts:169, avg_daily:24.1, fp_rate:0.333, total:3, good:2 },
      "2026-03-09": { alerts:199, avg_daily:28.4, fp_rate:null, total:0, good:0 },
      "2026-03-16": { alerts:121, avg_daily:24.2, fp_rate:0.25, total:4, good:3 },
    },
    "Wendy's 3323 - Selinsgrove": {
      "2026-02-09": { alerts:91, avg_daily:13.0, fp_rate:0.0, total:1, good:1 },
      "2026-02-16": { alerts:85, avg_daily:12.1, fp_rate:0.5, total:2, good:1 },
      "2026-02-23": { alerts:184, avg_daily:26.3, fp_rate:null, total:0, good:0 },
      "2026-03-02": { alerts:160, avg_daily:22.9, fp_rate:1.0, total:1, good:0 },
      "2026-03-09": { alerts:183, avg_daily:26.1, fp_rate:null, total:0, good:0 },
      "2026-03-16": { alerts:137, avg_daily:27.4, fp_rate:null, total:0, good:0 },
    },
    "Wendy's 585 - Lancaster Ave": {
      "2026-02-09": { alerts:96, avg_daily:13.7, fp_rate:0.333, total:3, good:2 },
      "2026-02-16": { alerts:101, avg_daily:14.4, fp_rate:0.5, total:4, good:2 },
      "2026-02-23": { alerts:144, avg_daily:20.6, fp_rate:0.0, total:2, good:2 },
      "2026-03-02": { alerts:196, avg_daily:28.0, fp_rate:0.4, total:5, good:3 },
      "2026-03-09": { alerts:168, avg_daily:24.0, fp_rate:null, total:0, good:0 },
      "2026-03-16": { alerts:100, avg_daily:20.0, fp_rate:0.0, total:1, good:1 },
    },
    "Wendy's 7798 - Academy Plaza": {
      "2026-02-09": { alerts:89, avg_daily:12.7, fp_rate:0.5, total:2, good:1 },
      "2026-02-16": { alerts:85, avg_daily:12.1, fp_rate:1.0, total:1, good:0 },
      "2026-02-23": { alerts:177, avg_daily:25.3, fp_rate:1.0, total:1, good:0 },
      "2026-03-02": { alerts:203, avg_daily:29.0, fp_rate:1.0, total:1, good:0 },
      "2026-03-09": { alerts:170, avg_daily:24.3, fp_rate:null, total:0, good:0 },
      "2026-03-16": { alerts:107, avg_daily:21.4, fp_rate:1.0, total:2, good:0 },
    },
  },
};
