// data.js
// This file is the single source of truth for dashboard data.
// LOGIN_DATA is auto-generated by pull_mixpanel.py --update-dashboard

export const WEEKS = ["Feb 2", "Feb 9", "Feb 16", "Feb 23", "Mar 2"];
export const WEEK_KEYS = ["2026-02-08", "2026-02-15", "2026-02-22", "2026-03-01", "2026-03-05"];
export const NEVER_LOGGED_IN = "Southern Tree";
export const TOTAL_CLIENTS = 12;

export const LOGIN_DATA = [
  { week: "Feb 2",  n: 7,  active: 12 },
  { week: "Feb 9",  n: 7,  active: 12 },
  { week: "Feb 16",  n: 10,  active: 12 },
  { week: "Feb 23",  n: 11,  active: 12 },
  { week: "Mar 2",  n: 10,  active: 12 }
].map(d => ({ ...d, pct: Math.round(d.n / d.active * 100) }));
export const SITE_DATA = {
  "Badia Spice LLC": {
    "1400": {
      "2026-02-15": { total:239, avg_daily:34.1, fp_rate:0.857, rated:21, good:3  },
      "2026-02-22": { total:66,  avg_daily:9.4,  fp_rate:1.0,   rated:4,  good:0  },
    },
  },
  "Conagra": {
    "St. Elmo": {
      "2026-02-01": { total:4,  avg_daily:0.6, fp_rate:0.5,  rated:4, good:2 },
      "2026-02-08": { total:3,  avg_daily:0.4, fp_rate:null, rated:0, good:0 },
      "2026-02-15": { total:5,  avg_daily:0.7, fp_rate:1.0,  rated:2, good:0 },
    },
    "Imlay City": {
      "2026-02-01": { total:9,  avg_daily:1.3, fp_rate:null, rated:0, good:0 },
      "2026-02-15": { total:11, avg_daily:1.6, fp_rate:null, rated:0, good:0 },
      "2026-02-22": { total:2,  avg_daily:0.3, fp_rate:null, rated:0, good:0 },
    },
  },
  "Mills": {
    "Mills Pilot": {
      "2026-02-01": { total:8,   avg_daily:1.1,  fp_rate:0.667, rated:3, good:1 },
      "2026-02-08": { total:18,  avg_daily:2.6,  fp_rate:0.0,   rated:1, good:1 },
      "2026-02-15": { total:131, avg_daily:18.7, fp_rate:0.556, rated:9, good:4 },
      "2026-02-22": { total:45,  avg_daily:6.4,  fp_rate:1.0,   rated:1, good:0 },
    },
  },
  "Shelby Erectors": {
    "Foreman Anibal S": {
      "2026-02-01": { total:7,  avg_daily:1.0, fp_rate:1.0,   rated:3, good:0 },
      "2026-02-08": { total:5,  avg_daily:0.7, fp_rate:null,  rated:0, good:0 },
      "2026-02-15": { total:11, avg_daily:1.6, fp_rate:0.667, rated:3, good:1 },
      "2026-02-22": { total:7,  avg_daily:1.0, fp_rate:0.5,   rated:2, good:1 },
    },
    "Foreman Jose Soto Hector": {
      "2026-02-01": { total:7, avg_daily:1.0, fp_rate:1.0,  rated:3, good:0 },
      "2026-02-08": { total:4, avg_daily:0.6, fp_rate:null, rated:0, good:0 },
      "2026-02-15": { total:8, avg_daily:1.1, fp_rate:0.2,  rated:5, good:4 },
      "2026-02-22": { total:3, avg_daily:0.4, fp_rate:null, rated:0, good:0 },
    },
    "Main Camera - Job 295": {
      "2026-02-01": { total:3,  avg_daily:0.4, fp_rate:null, rated:0, good:0 },
      "2026-02-08": { total:5,  avg_daily:0.7, fp_rate:null, rated:0, good:0 },
      "2026-02-15": { total:13, avg_daily:1.9, fp_rate:0.6,  rated:5, good:2 },
      "2026-02-22": { total:2,  avg_daily:0.3, fp_rate:null, rated:0, good:0 },
    },
  },
  "Southern Tree": {
    "Southern Tree Professionals, LLC": {
      "2026-02-01": { total:24, avg_daily:3.4, fp_rate:0.5,  rated:4, good:2 },
      "2026-02-08": { total:14, avg_daily:2.0, fp_rate:null, rated:0, good:0 },
    },
  },
  "Steel Service": {
    "Steel Service": {
      "2026-02-01": { total:81,  avg_daily:11.6, fp_rate:1.0,   rated:7,  good:0 },
      "2026-02-08": { total:93,  avg_daily:13.3, fp_rate:0.812, rated:16, good:3 },
      "2026-02-15": { total:167, avg_daily:23.9, fp_rate:1.0,   rated:15, good:0 },
      "2026-02-22": { total:38,  avg_daily:5.4,  fp_rate:1.0,   rated:3,  good:0 },
    },
  },
  "Stella Jones": {
    "Stella Jones": {
      "2026-02-01": { total:34, avg_daily:4.9, fp_rate:0.778, rated:18, good:4 },
      "2026-02-08": { total:30, avg_daily:4.3, fp_rate:0.7,   rated:10, good:3 },
      "2026-02-15": { total:19, avg_daily:2.7, fp_rate:0.75,  rated:4,  good:1 },
      "2026-02-22": { total:6,  avg_daily:0.9, fp_rate:null,  rated:0,  good:0 },
    },
  },
  "Stutsman": {
    "Stutsman - pilot": {
      "2026-02-01": { total:41, avg_daily:5.9, fp_rate:1.0,  rated:1, good:0 },
      "2026-02-08": { total:31, avg_daily:4.4, fp_rate:1.0,  rated:2, good:0 },
      "2026-02-15": { total:43, avg_daily:6.1, fp_rate:null, rated:0, good:0 },
      "2026-02-22": { total:18, avg_daily:2.6, fp_rate:null, rated:0, good:0 },
    },
  },
  "Thrift Holdings": {
    "Thrift Holdings - 29th Street": {
      "2026-02-01": { total:73, avg_daily:10.4, fp_rate:0.738, rated:42, good:11 },
      "2026-02-08": { total:83, avg_daily:11.9, fp_rate:0.645, rated:31, good:11 },
      "2026-02-15": { total:73, avg_daily:10.4, fp_rate:0.654, rated:26, good:9  },
      "2026-02-22": { total:37, avg_daily:5.3,  fp_rate:0.9,   rated:10, good:1  },
    },
    "Thrift Holdings - St Joseph": {
      "2026-02-01": { total:40, avg_daily:5.7, fp_rate:0.857, rated:7, good:1 },
      "2026-02-08": { total:44, avg_daily:6.3, fp_rate:0.333, rated:6, good:4 },
      "2026-02-15": { total:37, avg_daily:5.3, fp_rate:0.25,  rated:4, good:3 },
    },
  },
  "Tippmann": {
    "Indiana Packers DC-2": {
      "2026-02-01": { total:4,  avg_daily:0.6, fp_rate:1.0,  rated:1,  good:0 },
      "2026-02-08": { total:16, avg_daily:2.3, fp_rate:1.0,  rated:2,  good:0 },
      "2026-02-15": { total:43, avg_daily:6.1, fp_rate:0.8,  rated:15, good:3 },
      "2026-02-22": { total:4,  avg_daily:0.6, fp_rate:null, rated:0,  good:0 },
    },
  },
  "XPO": {
    "Leicester": {
      "2026-02-01": { total:157, avg_daily:22.4, fp_rate:0.933, rated:15, good:1 },
      "2026-02-08": { total:118, avg_daily:16.9, fp_rate:0.762, rated:21, good:5 },
      "2026-02-15": { total:148, avg_daily:21.1, fp_rate:0.7,   rated:10, good:3 },
      "2026-02-22": { total:53,  avg_daily:7.6,  fp_rate:null,  rated:0,  good:0 },
    },
  },
  "Yellow Cab": {
    "Wendy's 1017 - East York": {
      "2026-02-08": { total:61,  avg_daily:8.7,  fp_rate:0.846, rated:13, good:2 },
      "2026-02-15": { total:107, avg_daily:15.3, fp_rate:1.0,   rated:5,  good:0 },
      "2026-02-22": { total:90,  avg_daily:12.9, fp_rate:1.0,   rated:3,  good:0 },
    },
    "Wendy's 2074 - Hamburg": {
      "2026-02-08": { total:69, avg_daily:9.9,  fp_rate:0.571, rated:7, good:3 },
      "2026-02-15": { total:97, avg_daily:13.9, fp_rate:0.0,   rated:4, good:4 },
      "2026-02-22": { total:84, avg_daily:12.0, fp_rate:0.333, rated:3, good:2 },
    },
    "Wendy's 3323 - Selinsgrove": {
      "2026-02-08": { total:82, avg_daily:11.7, fp_rate:0.0,  rated:1, good:1 },
      "2026-02-15": { total:73, avg_daily:10.4, fp_rate:0.5,  rated:2, good:1 },
      "2026-02-22": { total:77, avg_daily:11.0, fp_rate:null, rated:0, good:0 },
    },
    "Wendy's 585 - Lancaster Ave": {
      "2026-02-08": { total:88, avg_daily:12.6, fp_rate:0.333, rated:3, good:2 },
      "2026-02-15": { total:93, avg_daily:13.3, fp_rate:0.5,   rated:4, good:2 },
      "2026-02-22": { total:60, avg_daily:8.6,  fp_rate:null,  rated:0, good:0 },
    },
    "Wendy's 7798 - Academy Plaza": {
      "2026-02-08": { total:83, avg_daily:11.9, fp_rate:0.5,  rated:2, good:1 },
      "2026-02-15": { total:76, avg_daily:10.9, fp_rate:null, rated:0, good:0 },
      "2026-02-22": { total:69, avg_daily:9.9,  fp_rate:null, rated:0, good:0 },
    },
  },
};
